
services:
  demo-app:
    build: .
    container_name: demo_app
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
