version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src  # 현재 경로를 /src로 마운트
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true